### PR TITLE
Linux 3.10.103

### PR DESCRIPTION
**Pull request by secuflag**

### CODE REVIEW

**Comment by ayufan** [comment]
Where did you get sources from?

**Comment by secuflag** [comment]
From kernel.org of course.
https://cdn.kernel.org/pub/linux/kernel/v3.x/incr/patch-3.10.102-103.xz

**Comment by ayufan** [comment]
I would probably prefer to use upstream changes from `longsleep/linux-pine64` to be as in-sync as possible.

**Comment by secuflag** [comment]
ok :thumbsup:

**Pull request closed without merging**
