### PR TITLE
enable CONFIG_SND_USB_AUDIO

### PR DESCRIPTION
**Pull request by mikey0000**
enables usb audio devices

### CODE REVIEW

**Comment by ayufan** [comment]
Why did you push Android.mk?

**Comment by mikey0000** [comment]
derp - wasn't supposed to do that here.

**Comment by ayufan** [comment]
Are you aware of that https://github.com/ayufan-pine64/device-softwinner/blob/nougat/tulip-chiphd/AndroidKernel.mk?

**Comment by mikey0000** [comment]
Yes, I am but I figured getting the kernel to build on its own outside the device tree was cleaner/tidyier/more android, Taking a note from how sony does it and most other aosp kernels as far as I know.

**Comment by ayufan** [comment]
Maybe, but I see a big value of kernel being a part of build process as this actually makes the build fully reproducible, instead of having binary blobs with unknown used kernel configuration.

**Comment by mikey0000** [comment]
With the Android.mk the kernel would be built along with everything else by default. It would then function the same as everything else, getting the modules copied into system/ etc its a bit of a WIP for me as the way allwinner compile their modules and the kernel is a bit foreign to me.

**Comment by ayufan** [comment]
I already did that with help of AndroidKernel.mk that I linked.

This is also a way that is used in other trees (ex. http://androidxref.com/7.0.0_r1/xref/device/asus/fugu/AndroidKernel.mk) :)

**Comment by ayufan** [comment]
I use longsleep kernel and compile everything that is required for it to function.

**Comment by mikey0000** [comment]
removed Android.mk, Great work on integrating the kernel as part of the normal build process! Well TIL (today i learned) Sweet I'm happy then :D

**Pull request merged**
